"use client";
import { useEffect, useMemo, useState } from "react";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";

import mainTheme from "@/theme";
import NavBar from "@/components/NavBar";
import Modal from "@/components/Modal/Modal";
import StoreProvider from "@/redux/StoreProvider";

// export const metadata = {
//   title: "Quaestio Web",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [colorMode, setColorMode] = useState("light");
  const theme = useMemo(
    () =>
      createTheme({
        ...mainTheme,
        palette: {
          mode: colorMode,
        },
      }),
    [colorMode]
  );

  const handleSetColorMode = (mode) => {
    localStorage.setItem("colorMode", mode);
    setColorMode(mode);
  };

  useEffect(() => {
    const mode = localStorage.getItem("colorMode");
    mode && setColorMode(mode);
  }, []);

  return (
    <html lang="en" style={{ height: "100%" }}>
      <StoreProvider>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <body
            style={{
              height: "100%",
              display: "flex",
              flexDirection: "column",
            }}
          >
            <NavBar colorMode={colorMode} setColorMode={handleSetColorMode} />
            {children}
            <Modal />
          </body>
        </ThemeProvider>
      </StoreProvider>
    </html>
  );
}
