"use client";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import { store } from "@/redux/store";
import { Provider } from "react-redux";
import { useMemo, useState } from "react";
import CssBaseline from "@mui/material/CssBaseline";
import mainTheme from "@/theme";

import NavBar from "@/components/NavBar";
import Modal from "@/components/Modal/Modal";

// export const metadata = {
//   title: 'Quaestio Web',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [colorMode, setColorMode] = useState("light");
  console.log("colorMode", colorMode);
  const theme = useMemo(
    () =>
      createTheme({
        ...mainTheme,
        palette: {
          mode: colorMode,
        },
      }),
    [colorMode]
  );

  const handleSetColorMode = (mode) => {
    setColorMode(mode ? "dark" : "light");
  };

  return (
    <html lang="en" style={{ height: "100%" }}>
      <Provider store={store}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <body
            style={{ height: "100%", display: "flex", flexDirection: "column" }}
          >
            <NavBar setColorMode={handleSetColorMode} />
            {children}
            <Modal />
          </body>
        </ThemeProvider>
      </Provider>
    </html>
  );
}
