"use client";
import "./globals.css";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import { Inter } from "next/font/google";
import { store } from "@/src/redux/store";
import { Provider, useDispatch } from "react-redux";
import { useEffect } from "react";
import CssBaseline from "@mui/material/CssBaseline";

import { loadQuestionarie } from "@/src/redux/questionaireThunks";
import { openModal } from "@/src/redux/modalSlice";

const inter = Inter({ subsets: ["latin"] });

const darkTheme = createTheme({
  palette: {
    mode: "dark",
  },
});

// export const metadata = {
//   title: 'Quaestio Web',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  useEffect(() => {
    (async () => {
      try {
        await store.dispatch(loadQuestionarie()).unwrap();
      } catch (e) {
        if (e.code === "ERR_BAD_REQUEST") {
          store.dispatch(openModal("file"));
        }
      }
    })();
  }, []);

  return (
    <html lang="en">
      <Provider store={store}>
        <ThemeProvider theme={darkTheme}>
          <CssBaseline />
          <body className={inter.className}>{children}</body>
        </ThemeProvider>
      </Provider>
    </html>
  );
}
